#############################################################################

# Makefile for building Kacca
# Generated by tmake at 00:10, 2008/11/12
#     Project: Kacca
#    Template: app
#############################################################################

####### Compiler, tools and options
QT += network
QTDIR	=	/usr
CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -O2 -D_REENTRANT -DIBASE -DQT_THREAD_SUPPORT -DNO_DEBUG -Wno-deprecated -DLINUX_BUILD
CXXFLAGS=	-pipe -O2 -D_REENTRANT -DIBASE -DQT_THREAD_SUPPORT -DNO_DEBUG -Wno-deprecated -DLINUX_BUILD
INCPATH	=	-I$(QTDIR)/include/qt3 -I./include -I$(QTDIR)/include/PCX-1.8
LINK	=	g++
LFLAGS	=
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -L$(QTDIR)/lib/PCX-1.8 -lxbase -lgds -lcrypt -ldl -lpthread -lqt-mt -lXext -lX11 -lm -luuid -llinpcx -llog4cplus -lssl -lqrencode
#LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -L$(QTDIR)/lib/PCX-1.8 -lxbase -lgds -lcrypt -ldl -lpthread -lqt-mt -lXext -lX11 -lm -luuid -llinpcx -llog4cplus -lssl 
#LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -L$(QTDIR)/lib/PCX-1.8 -lxbase -lgds -lcrypt -ldl -lpthread -lqt-mt -lXext -lX11 -lm -luuid
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic
OBJDIR  =	.

TAR	=	tar -cf
GZIP	=	gzip -9f

DESTDIR	=
BIN	=	$(DESTDIR)/Kacca
####### Files

HEADERS =	include/Cash.h \
		include/Passwd.h \
		include/Sum.h \
		include/AbstractFiscalReg.h \
		include/EmptyFiscalReg.h \
		include/ElvisFiscalRegVer2.h \
		include/ElvisFiscalRegVer3.h \
		include/ElvisFiscalRegVer3Printer.h \
		include/Fiscal.h \
		include/DbfTable.h \
		include/Utils.h \
		include/CheckSearch.h \
		include/Return.h \
		include/Login.h \
		include/PortSelect.h \
		include/WorkPlace.h \
		include/Display.h \
		include/Scale.h \
		include/Guard.h \
		include/Actsiz.h \
		include/PriceSel.h \
		include/SectionSel.h \
		include/Calc.h \
		include/Search.h \
		include/Payment.h \
		include/Spec.h \
		include/Threads.h \
		include/Ping.h \
		include/PaymentType.h \
		include/DateShift.h \
		include/ShiftRange.h \
		include/DateRange.h \
		include/Exclamation.h \
		include/RegTable.h \
		include/Message.h \
		include/ExtControls.h \
		include/FreeSum.h \
		include/BankBonus.h \
		include/ChangeForm.h \
		include/ScreenSaver.h \
		include/PCX.h \
		include/Bonus.h \
		include/posDBXBase.h \
		include/EGAISCheck_dlg.h \
		include/ QrCode.h
		
SOURCES =	main.cpp \
		posDBXBase.cpp \
		Cash.cpp \
		Passwd.cpp \
		Sum.cpp \
		EmptyFiscalReg.cpp \
		ElvisFiscalRegVer2.cpp \
		ElvisFiscalRegVer3.cpp \
		ElvisFiscalRegVer3Printer.cpp \
		DbfTable.cpp \
		Utils.cpp \
		CheckSearch.cpp \
		Return.cpp \
		Login.cpp \
		PortSelect.cpp \
		WorkPlace.cpp \
		Display.cpp \
		Scale.cpp \
		Guard.cpp \
		Actsiz.cpp \
		PriceSel.cpp \
		SectionSel.cpp \
		Calc.cpp \
		Search.cpp \
		Payment.cpp \
		Threads.cpp \
		Ping.cpp \
		PaymentType.cpp \
		DateShift.cpp \
		ShiftRange.cpp \
		DateRange.cpp \
		Exclamation.cpp \
		RegTable.cpp \
		Message.cpp \
		ExtControls.cpp\
		FreeSum.cpp\
		BankBonus.cpp\
		ChangeForm.cpp\
		ScreenSaver.cpp\
		PCX.cpp\
		Bonus.cpp\
		Revision.cpp \
		EGAISCheck_dlg.cpp \
		QrCode.cpp

OBJECTS =	main.o \
		posDBXBase.o \
		Cash.o \
		Passwd.o \
		Sum.o \
		EmptyFiscalReg.o \
		ElvisFiscalRegVer2.o \
		ElvisFiscalRegVer3.o \
		ElvisFiscalRegVer3Printer.o \
		DbfTable.o \
		Utils.o \
		CheckSearch.o \
		Return.o \
		Login.o \
		PortSelect.o \
		WorkPlace.o \
		Display.o \
		Scale.o \
		Guard.o \
		Actsiz.o \
		PriceSel.o \
		SectionSel.o \
		Calc.o \
		Search.o \
		Payment.o \
		Threads.o \
		Ping.o \
		PaymentType.o \
		DateShift.o \
		ShiftRange.o \
		DateRange.o \
		Exclamation.o \
		RegTable.o \
		Message.o \
		ExtControls.o \
		FreeSum.o \
		BankBonus.o\
		ChangeForm.o\
		ScreenSaver.o\
		PCX.o\
		Bonus.o\
		Revision.o \
		EGAISCheck_dlg.o \
		QrCode.o

INTERFACES =
UICDECLS =
UICIMPLS =
SRCMOC	=	moc_Cash.cpp \
		moc_Passwd.cpp \
		moc_Sum.cpp \
		moc_CheckSearch.cpp \
		moc_Return.cpp \
		moc_Login.cpp \
		moc_PortSelect.cpp \
		moc_WorkPlace.cpp \
		moc_Guard.cpp \
		moc_Actsiz.cpp \
		moc_PriceSel.cpp \
		moc_SectionSel.cpp \
		moc_Calc.cpp \
		moc_Search.cpp \
		moc_Payment.cpp \
		moc_PaymentType.cpp \
		moc_DateShift.cpp \
		moc_ShiftRange.cpp \
		moc_DateRange.cpp \
		moc_Exclamation.cpp \
		moc_RegTable.cpp \
		moc_Message.cpp \
		moc_FreeSum.cpp \
		moc_BankBonus.cpp\
		moc_ChangeForm.cpp\
		moc_ScreenSaver.cpp\
		moc_ExtControls.cpp \
		moc_QrCode.cpp
OBJMOC	=	moc_Cash.o \
		moc_Passwd.o \
		moc_Sum.o \
		moc_CheckSearch.o \
		moc_Return.o \
		moc_Login.o \
		moc_PortSelect.o \
		moc_WorkPlace.o \
		moc_Guard.o \
		moc_Actsiz.o \
		moc_PriceSel.o \
		moc_SectionSel.o \
		moc_Calc.o \
		moc_Search.o \
		moc_Payment.o \
		moc_PaymentType.o \
		moc_DateShift.o \
		moc_ShiftRange.o \
		moc_DateRange.o \
		moc_Exclamation.o \
		moc_RegTable.o \
		moc_Message.o \
		moc_FreeSum.o \
		moc_BankBonus.o\
		moc_ChangeForm.o\
		moc_ScreenSaver.o\
		moc_ExtControls.o \
		moc_EGAISCheck_dlg.o \
		moc_QrCode.o
DIST	=
TARGET	=	Kacca
TARGETTEST	=	KaccaTest
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJDIR)/$@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJDIR)/$@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJDIR)/$@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJDIR)/$@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $(OBJDIR)/$@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)


Release: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

Debug: $(TARGETTEST)

$(TARGETTEST): $(UICDECLS) $(OBJECTS) $(OBJMOC)
	$(LINK) $(LFLAGS) -o $(TARGETTEST) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: makefile

makefile: Kacca.pro
	tmake Kacca.pro -o makefile

dist:
	$(TAR) Kacca.tar Kacca.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) Kacca.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

cleanall:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(SOURCES) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

# Для того, чтобы выполнить это, вы должны иметь права пользователя root!
install: $(TARGET)
	install -d $(BIN)
#install -d $(BIN) $(ICONS) $(DESTDIR)/etc
	install ./Kacca $(BIN)
#install -m644 icons/* $(ICONS)
#install -m644 gentoorc-example $(DESTDIR)/etc/gentoorc
#install -d $(DESTDIR)/usr/share/doc/gentoo/html
#cp -a docs/* $(DESTDIR)/usr/share/doc/gentoo/html
####### Sub-libraries


###### Combined headers


####### Compile

$(OBJDIR)/main.o: main.cpp \
		include/Cash.h \
		include/Spec.h \
		include/Threads.h \
		include/Utils.h \
		include/ExtControls.h \
		include/Display.h \
		include/WorkPlace.h

$(OBJDIR)/Cash.o: Cash.cpp \
		Revision.cpp \
		include/Cash.h \
		include/Spec.h \
		include/Threads.h \
		include/Utils.h \
		include/ExtControls.h \
		include/Display.h \
		include/Passwd.h \
		include/Sum.h \
		include/Fiscal.h \
		include/AbstractFiscalReg.h \
		include/EmptyFiscalReg.h \
		include/ElvisFiscalRegVer2.h \
		include/ElvisFiscalRegVer3.h \
		include/ElvisFiscalRegVer3Printer.h \
		include/CheckSearch.h \
		include/Return.h \
		include/Login.h \
		include/PortSelect.h \
		include/WorkPlace.h \
		include/DbfTable.h \
		include/Search.h \
		include/Payment.h \
		include/DateShift.h \
		include/ShiftRange.h \
		include/DateRange.h \
		include/RegTable.h \
		include/Guard.h \
		include/FreeSum.h \
		include/BankBonus.h \
		include/ScreenSaver.h \
		include/PCX.h \
		include/Bonus.h \
		include/ChangeForm.h \
		include/Ping.h

$(OBJDIR)/Passwd.o: Passwd.cpp \
		include/Passwd.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/PCX.o: PCX.cpp \
		include/PCX.h

$(OBJDIR)/Bonus.o: Bonus.cpp \
		include/Bonus.h

$(OBJDIR)/Sum.o: Sum.cpp \
		include/Sum.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/EmptyFiscalReg.o: EmptyFiscalReg.cpp \
		include/Utils.h \
		include/Spec.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Display.h \
		include/DbfTable.h

$(OBJDIR)/ElvisFiscalRegVer2.o: ElvisFiscalRegVer2.cpp \
		include/ElvisFiscalRegVer2.h \
		include/Spec.h \
		include/EmptyFiscalReg.h \
		include/AbstractFiscalReg.h \
		include/Utils.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Display.h \
		include/DbfTable.h

$(OBJDIR)/ElvisFiscalRegVer3.o: ElvisFiscalRegVer3.cpp \
		include/ElvisFiscalRegVer3.h \
		include/Spec.h \
		include/EmptyFiscalReg.h \
		include/AbstractFiscalReg.h \
		include/Utils.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Display.h \
		include/DbfTable.h

$(OBJDIR)/ElvisFiscalRegVer3Printer.o: ElvisFiscalRegVer3Printer.cpp \
		include/ElvisFiscalRegVer3Printer.h \
		include/Spec.h \
		include/EmptyFiscalReg.h \
		include/AbstractFiscalReg.h \
		include/Utils.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Display.h \
		include/DbfTable.h

$(OBJDIR)/DbfTable.o: DbfTable.cpp \
		include/DbfTable.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/Utils.o: Utils.cpp \
		include/Utils.h \
		include/Spec.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Display.h

$(OBJDIR)/CheckSearch.o: CheckSearch.cpp \
		include/CheckSearch.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/Return.o: Return.cpp \
		include/Return.h \
		include/Utils.h \
		include/Spec.h \
		include/Sum.h

$(OBJDIR)/Login.o: Login.cpp \
		include/Login.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/PortSelect.o: PortSelect.cpp \
		include/PortSelect.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/WorkPlace.o: WorkPlace.cpp \
		Revision.cpp \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/ExtControls.h \
		include/Display.h \
		include/Scale.h \
		include/Fiscal.h \
		include/AbstractFiscalReg.h \
		include/EmptyFiscalReg.h \
		include/ElvisFiscalRegVer2.h \
		include/ElvisFiscalRegVer3.h \
		include/ElvisFiscalRegVer3Printer.h \
		include/Guard.h \
		include/Actsiz.h \
		include/PriceSel.h \
		include/SectionSel.h \
		include/Calc.h \
		include/Search.h \
		include/Payment.h \
		include/Cash.h \
		include/Threads.h \
		include/DbfTable.h \
		include/PaymentType.h \
		include/Ping.h \
		include/Sum.h \
		include/Message.h \
		include/FreeSum.h \
		include/BankBonus.h \
		include/ChangeForm.h \
		include/ScreenSaver.h \
		include/PCX.h \
		include/Bonus.h \
		include/posDBXBase.h

$(OBJDIR)/Display.o: Display.cpp \
		include/Display.h \
		include/Spec.h \
		include/Utils.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Fiscal.h \
		include/AbstractFiscalReg.h \
		include/EmptyFiscalReg.h \
		include/ElvisFiscalRegVer2.h \
		include/ElvisFiscalRegVer3.h \
		include/ElvisFiscalRegVer3Printer.h \
		include/DbfTable.h \
		include/WorkPlace.h

$(OBJDIR)/Scale.o: Scale.cpp \
		include/Scale.h \
		include/Spec.h \
		include/Utils.h

$(OBJDIR)/Guard.o: Guard.cpp \
		include/Guard.h \
		include/Utils.h \
		include/Spec.h \
		include/ExtControls.h

$(OBJDIR)/PriceSel.o: PriceSel.cpp \
		include/PriceSel.h \
		include/Utils.h \
		include/Spec.h \
		include/ExtControls.h

$(OBJDIR)/SectionSel.o: SectionSel.cpp \
		include/SectionSel.h \
		include/ExtControls.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/Calc.o: Calc.cpp \
		include/Calc.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/Search.o: Search.cpp \
		include/Search.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/PriceSel.h

$(OBJDIR)/FreeSum.o: FreeSum.cpp \
		include/FreeSum.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/PriceSel.h

$(OBJDIR)/BankBonus.o: BankBonus.cpp \
		include/BankBonus.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/PriceSel.h

$(OBJDIR)/ChangeForm.o: ChangeForm.cpp \
		include/ChangeForm.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/PriceSel.h

$(OBJDIR)/Payment.o: Payment.cpp \
		include/Payment.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/PriceSel.h

$(OBJDIR)/Threads.o: Threads.cpp \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/ExtControls.h \
		include/Threads.h \
		include/Search.h \
		include/Cash.h \
		include/Display.h \
		include/Guard.h \
		include/DbfTable.h \
		include/Ping.h \
		include/Exclamation.h

$(OBJDIR)/Ping.o: Ping.cpp \
		include/Utils.h \
		include/Spec.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Display.h \
		include/Ping.h

$(OBJDIR)/PaymentType.o: PaymentType.cpp \
		include/PaymentType.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/DateShift.o: DateShift.cpp \
		include/DateShift.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/ShiftRange.o: ShiftRange.cpp \
		include/ShiftRange.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/DateRange.o: DateRange.cpp \
		include/DateRange.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/Exclamation.o: Exclamation.cpp \
		include/Exclamation.h \
		include/ExtControls.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/RegTable.o: RegTable.cpp \
		include/RegTable.h \
		include/Utils.h \
		include/Spec.h \
		include/Cash.h \
		include/Threads.h \
		include/ExtControls.h \
		include/Display.h \
		include/Fiscal.h \
		include/AbstractFiscalReg.h \
		include/EmptyFiscalReg.h \
		include/ElvisFiscalRegVer2.h \
		include/ElvisFiscalRegVer3.h \
		include/ElvisFiscalRegVer3Printer.h

$(OBJDIR)/Message.o: Message.cpp \
		include/Message.h \
		include/ExtControls.h \
		include/Utils.h \
		include/Spec.h

$(OBJDIR)/ExtControls.o: ExtControls.cpp \
		include/ExtControls.h \
		include/Utils.h \
		include/Spec.h \
		include/WorkPlace.h \
		include/Cash.h \
		include/Threads.h \
		include/Display.h

$(OBJDIR)/moc_Cash.o: moc_Cash.cpp \
		include/Cash.h \
		include/Spec.h \
		include/Threads.h \
		include/Utils.h \
		include/ExtControls.h \
		include/Display.h

$(OBJDIR)/moc_EGAISCheck_dlg.o: moc_EGAISCheck_dlg.cpp \
		include/EGAISCheck_dlg.h \
		include/DbfTable.h \
		include/Utils.h \
		include/Cash.h \
		include/Threads.h
		
$(OBJDIR)/moc_QrCode.o: moc_QrCode.cpp \
		include/QrCode.h
		include/Utils.h \
		include/Cash.h

moc_Passwd.o: moc_Passwd.cpp \
		include/Passwd.h

moc_Sum.o: moc_Sum.cpp \
		include/Sum.h

moc_CheckSearch.o: moc_CheckSearch.cpp \
		include/CheckSearch.h

moc_Return.o: moc_Return.cpp \
		include/Return.h

moc_Login.o: moc_Login.cpp \
		include/Login.h

moc_PortSelect.o: moc_PortSelect.cpp \
		include/PortSelect.h

moc_WorkPlace.o: moc_WorkPlace.cpp \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h \
		include/ExtControls.h

moc_Guard.o: moc_Guard.cpp \
		include/Guard.h

moc_Actsiz.o: moc_Actsiz.cpp \
		include/Actsiz.h

moc_PriceSel.o: moc_PriceSel.cpp \
		include/PriceSel.h

moc_SectionSel.o: moc_SectionSel.cpp \
		include/SectionSel.h

moc_Calc.o: moc_Calc.cpp \
		include/Calc.h

moc_Search.o: moc_Search.cpp \
		include/Search.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h

moc_FreeSum.o: moc_FreeSum.cpp \
		include/FreeSum.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h

moc_BankBonus.o: moc_BankBonus.cpp \
		include/BankBonus.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h

moc_ChangeForm.o: moc_ChangeForm.cpp \
		include/ChangeForm.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h

moc_ScreenSaver.o: moc_ScreenSaver.cpp \
		include/ScreenSaver.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h

moc_Payment.o: moc_Payment.cpp \
		include/Payment.h \
		include/ExtControls.h \
		include/WorkPlace.h \
		include/Utils.h \
		include/Spec.h

moc_PaymentType.o: moc_PaymentType.cpp \
		include/PaymentType.h

moc_DateShift.o: moc_DateShift.cpp \
		include/DateShift.h

moc_ShiftRange.o: moc_ShiftRange.cpp \
		include/ShiftRange.h

moc_DateRange.o: moc_DateRange.cpp \
		include/DateRange.h

moc_Exclamation.o: moc_Exclamation.cpp \
		include/Exclamation.h

moc_RegTable.o: moc_RegTable.cpp \
		include/RegTable.h

moc_Message.o: moc_Message.cpp \
		include/Message.h

moc_ExtControls.o: moc_ExtControls.cpp \
		include/ExtControls.h

moc_Cash.cpp: include/Cash.h
	$(MOC) include/Cash.h -o moc_Cash.cpp

moc_Passwd.cpp: include/Passwd.h
	$(MOC) include/Passwd.h -o moc_Passwd.cpp

moc_Sum.cpp: include/Sum.h
	$(MOC) include/Sum.h -o moc_Sum.cpp

moc_CheckSearch.cpp: include/CheckSearch.h
	$(MOC) include/CheckSearch.h -o moc_CheckSearch.cpp

moc_Return.cpp: include/Return.h
	$(MOC) include/Return.h -o moc_Return.cpp

moc_Login.cpp: include/Login.h
	$(MOC) include/Login.h -o moc_Login.cpp

moc_PortSelect.cpp: include/PortSelect.h
	$(MOC) include/PortSelect.h -o moc_PortSelect.cpp

moc_WorkPlace.cpp: include/WorkPlace.h
	$(MOC) include/WorkPlace.h -o moc_WorkPlace.cpp

moc_Guard.cpp: include/Guard.h
	$(MOC) include/Guard.h -o moc_Guard.cpp

moc_Actsiz.cpp: include/Actsiz.h
	$(MOC) include/Actsiz.h -o moc_Actsiz.cpp

moc_PriceSel.cpp: include/PriceSel.h
	$(MOC) include/PriceSel.h -o moc_PriceSel.cpp

moc_SectionSel.cpp: include/SectionSel.h
	$(MOC) include/SectionSel.h -o moc_SectionSel.cpp

moc_Calc.cpp: include/Calc.h
	$(MOC) include/Calc.h -o moc_Calc.cpp

moc_Search.cpp: include/Search.h
	$(MOC) include/Search.h -o moc_Search.cpp

moc_FreeSum.cpp: include/FreeSum.h
	$(MOC) include/FreeSum.h -o moc_FreeSum.cpp

moc_BankBonus.cpp: include/BankBonus.h
	$(MOC) include/BankBonus.h -o moc_BankBonus.cpp

moc_ChangeForm.cpp: include/ChangeForm.h
	$(MOC) include/ChangeForm.h -o moc_ChangeForm.cpp

moc_ScreenSaver.cpp: include/ScreenSaver.h
	$(MOC) include/ScreenSaver.h -o moc_ScreenSaver.cpp

moc_Payment.cpp: include/Payment.h
	$(MOC) include/Payment.h -o moc_Payment.cpp

moc_PaymentType.cpp: include/PaymentType.h
	$(MOC) include/PaymentType.h -o moc_PaymentType.cpp

moc_DateShift.cpp: include/DateShift.h
	$(MOC) include/DateShift.h -o moc_DateShift.cpp

moc_ShiftRange.cpp: include/ShiftRange.h
	$(MOC) include/ShiftRange.h -o moc_ShiftRange.cpp

moc_DateRange.cpp: include/DateRange.h
	$(MOC) include/DateRange.h -o moc_DateRange.cpp

moc_Exclamation.cpp: include/Exclamation.h
	$(MOC) include/Exclamation.h -o moc_Exclamation.cpp

moc_RegTable.cpp: include/RegTable.h
	$(MOC) include/RegTable.h -o moc_RegTable.cpp

moc_Message.cpp: include/Message.h
	$(MOC) include/Message.h -o moc_Message.cpp

moc_ExtControls.cpp: include/ExtControls.h
	$(MOC) include/ExtControls.h -o moc_ExtControls.cpp

moc_EGAISCheck_dlg.cpp: include/EGAISCheck_dlg.h
	$(MOC) include/EGAISCheck_dlg.h -o moc_EGAISCheck_dlg.cpp
	
moc_QrCode.cpp: include/QrCode.h	
	$(MOC) include/QrCode.h -o moc_QrCode.cpp
	